### ISSUE TITLE
Add support for node 8

### ISSUE THREAD

**Issue by molant** [chearon/node-canvas-prebuilt#11]
[node 8 has been released](https://nodejs.org/en/blog/release/v8.0.0/), it will be great to have the packages for this version :)

**Comment by kazazor** [comment]
I'll add to that, we're currently getting this error:
```shell
canvas-prebuilt@1.6.5-prerelease.1 install /Users/orkazaz/Developments/Autodesk/BIM360/quality-ui-web/node_modules/canvas-prebuilt
> node-pre-gyp install

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.5-prerelease.1/canvas-prebuilt-v1.6.5-prerelease.1-node-v57-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/orkazaz/Developments/Autodesk/BIM360/quality-ui-web/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at emitOne (events.js:120:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:210:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/orkazaz/Developments/Autodesk/BIM360/quality-ui-web/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at emitOne (events.js:115:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:210:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:563:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:452:20)
node-pre-gyp ERR! stack     at emitOne (events.js:115:13)
node-pre-gyp ERR! System Darwin 16.6.0
node-pre-gyp ERR! command "/Users/orkazaz/.nvm/versions/node/v8.0.0/bin/node" "/Users/orkazaz/Developments/Autodesk/BIM360/quality-ui-web/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /Users/orkazaz/Developments/Autodesk/BIM360/quality-ui-web/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v8.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.5-prerelease.1/canvas-prebuilt-v1.6.5-prerelease.1-node-v57-darwin-x64.tar.gz
```

So this is actually a blocker for us to upgrade to Node 8 with npm 5 :/

**Comment by chearon** [comment]
I just have to add 8 to the build list and re-run on Travis. I plan on doing it today, will update this issue when I'm done

**Comment by chearon** [comment]
Sorry for the wait

Added node 8 to the old build (affected by #6 but can use an old version of GLib):
* 1.4.0
* 1.5.0
* 1.6.0

And to the new build (not affected by #6 but requires GLib >~ 2.44)
* 1.6.5-prerelease.1

**Comment by molant** [comment]
Thanks @chearon !
