### ISSUE TITLE
Error on start after latest update

### ISSUE THREAD

**Issue by yofreke** [chearon/node-canvas-prebuilt#7]
As of publishing, update was ~1hr ago, `1.6.15`.

```
Error: Cannot find module 'parse-css-font'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/canvas-prebuilt/canvas/lib/context2d.js:19:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/canvas-prebuilt/canvas/lib/canvas.js:17:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by chearon** [comment]
I just unpublished `1.6.15`, it should work now. Canvas introduced JS dependencies in 1.6.5 and I'm having issues getting that to work, for now everyone will have to keep using `1.6.0`
